# Generated by Django 4.2 on 2025-06-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banque', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptebancaire',
            old_name='client_banque',
            new_name='client',
        ),
        migrations.AddField(
            model_name='clientbanque',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
