# Generated by Django 4.2 on 2025-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0003_rename_client_banque_comptebancaire_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptebancaire',
            name='numero_compte',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
