# Generated by Django 4.2 on 2025-06-12 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banque', '0004_alter_comptebancaire_numero_compte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_transaction'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('Terminé', 'Terminé'), ('Échoué', 'Échoué'), ('En attente', 'En attente')], default='Terminé', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
