# Generated by Django 5.2.7 on 2026-06-06 03:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0002_initial'),
        ('sale', '0010_facture_uuid_paiementligne_callback_received_and_more'),
        ('store', '0005_alter_marquepureteprixhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone_client', models.CharField(max_length=30)),
                ('email_client', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecommerce', to='store.bijouterie')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecommerce', to='sale.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_ecommerce_creees', to=settings.AUTH_USER_MODEL)),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_ecommerce', to='sale.facture')),
                ('vente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_ecommerce', to='sale.vente')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeEcommerceLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='e_commerce.commandeecommerce')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecommerce', to='store.produit')),
                ('produit_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecommerce', to='purchase.produitline')),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_preparation', 'En préparation'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('annule', 'Annulé')], db_index=True, default='en_preparation', max_length=30)),
                ('adresse_livraison', models.TextField()),
                ('telephone_client', models.CharField(max_length=30)),
                ('transporteur', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=150, null=True)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='e_commerce.commandeecommerce')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference_paiement', models.CharField(blank=True, db_index=True, max_length=150)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='e_commerce.commandeecommerce')),
            ],
        ),
    ]
