# Generated by Django 5.2.7 on 2026-10-07 11:26

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone_client', models.CharField(max_length=30)),
                ('email_client', models.EmailField(max_length=254)),
                ('adresse_livraison', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20)),
                ('appliquer_tva', models.BooleanField(default=False)),
                ('taux_tva', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total HT des produits.', max_digits=14)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='montant_total + montant_tva + frais_transaction', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandeEcommerceLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_gramme', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EcommerceBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('sous_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='ecommerce/banners/')),
                ('texte_bouton', models.CharField(blank=True, max_length=100, null=True)),
                ('lien_action', models.CharField(blank=True, max_length=500, null=True)),
                ('ordre_affichage', models.PositiveIntegerField(db_index=True, default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bannière e-commerce',
                'verbose_name_plural': 'Bannières e-commerce',
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcommerceBannerNouveauArrivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('sous_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], db_index=True, default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecommerce/nouveaux_arrivages/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ecommerce/nouveaux_arrivages/videos/')),
                ('texte_bouton', models.CharField(blank=True, max_length=100, null=True)),
                ('lien_action', models.CharField(blank=True, max_length=500, null=True)),
                ('ordre_affichage', models.PositiveIntegerField(db_index=True, default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nouveau arrivage e-commerce',
                'verbose_name_plural': 'Nouveaux arrivages e-commerce',
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivraisonEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('en_preparation', 'En préparation'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('annule', 'Annulé')], db_index=True, default='en_preparation', max_length=30)),
                ('adresse_livraison', models.TextField()),
                ('telephone_client', models.CharField(max_length=30)),
                ('transporteur', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference_paiement', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
