# Generated by Django 5.2.7 on 2026-08-06 21:20

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone_client', models.CharField(max_length=30)),
                ('email_client', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeEcommerceLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_gramme', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='EcommerceBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], db_index=True, default='image', max_length=20)),
                ('position', models.CharField(choices=[('grande_banniere', 'Grande bannière accueil'), ('nouveau_arrivage', 'Bannière nouveau arrivage'), ('banniere_video', 'Bannière vidéo'), ('promotion', 'Bannière promotion')], db_index=True, default='grande_banniere', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecommerce/banners/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ecommerce/banners/videos/')),
                ('lien_action', models.URLField(blank=True, null=True)),
                ('texte_bouton', models.CharField(blank=True, max_length=80, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcommerceHomeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('featured', 'Produits sélectionnés'), ('new_arrival', 'Nouveaux arrivages'), ('slider', 'Carrousel'), ('best_seller', 'Meilleures ventes')], db_index=True, default='featured', max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('titre_personnalise', models.CharField(blank=True, max_length=150, null=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('image_personnalisee', models.ImageField(blank=True, null=True, upload_to='ecommerce/home/produits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivraisonEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('en_preparation', 'En préparation'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('annule', 'Annulé')], db_index=True, default='en_preparation', max_length=30)),
                ('adresse_livraison', models.TextField()),
                ('telephone_client', models.CharField(max_length=30)),
                ('transporteur', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=150, null=True)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference_paiement', models.CharField(blank=True, db_index=True, max_length=150)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
