# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commerce', '0001_initial'),
        ('sale', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeecommerce',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecommerce', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='commandeecommerce',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecommerce', to='sale.client'),
        ),
    ]
