# Generated by Django 5.2.7 on 2026-10-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commerce', '0001_initial'),
        ('purchase', '0001_initial'),
        ('sale', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeecommerce',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecommerce', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='commandeecommerce',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecommerce', to='sale.client'),
        ),
        migrations.AddField(
            model_name='commandeecommerce',
            name='facture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_ecommerce', to='sale.facture'),
        ),
        migrations.AddField(
            model_name='commandeecommerce',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_ecommerce', to='sale.vente'),
        ),
        migrations.AddField(
            model_name='commandeecommerceligne',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='e_commerce.commandeecommerce'),
        ),
        migrations.AddField(
            model_name='commandeecommerceligne',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecommerce', to='store.produit'),
        ),
        migrations.AddField(
            model_name='commandeecommerceligne',
            name='produit_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecommerce', to='purchase.produitline'),
        ),
        migrations.AddIndex(
            model_name='ecommercebanner',
            index=models.Index(fields=['active', 'ordre_affichage'], name='e_commerce__active_fdce85_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommercebannernouveauarrivage',
            index=models.Index(fields=['active', 'ordre_affichage'], name='e_commerce__active_c641fa_idx'),
        ),
        migrations.AddField(
            model_name='livraisonecommerce',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='e_commerce.commandeecommerce'),
        ),
        migrations.AddField(
            model_name='paiementecommerce',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='e_commerce.commandeecommerce'),
        ),
        migrations.AddIndex(
            model_name='commandeecommerce',
            index=models.Index(fields=['status'], name='e_commerce__status_18be8d_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeecommerce',
            index=models.Index(fields=['bijouterie', 'status'], name='e_commerce__bijoute_5f1e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeecommerce',
            index=models.Index(fields=['created_at'], name='e_commerce__created_c8fa5b_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeecommerce',
            index=models.Index(fields=['telephone_client'], name='e_commerce__telepho_c010fc_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeecommerceligne',
            index=models.Index(fields=['commande'], name='e_commerce__command_633398_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeecommerceligne',
            index=models.Index(fields=['produit_line'], name='e_commerce__produit_c67b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeecommerceligne',
            index=models.Index(fields=['produit'], name='e_commerce__produit_c76101_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementecommerce',
            index=models.Index(fields=['commande', 'status'], name='e_commerce__command_f4e701_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementecommerce',
            index=models.Index(fields=['mode', 'status'], name='e_commerce__mode_77c529_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementecommerce',
            index=models.Index(fields=['created_at'], name='e_commerce__created_b437b4_idx'),
        ),
    ]
