# Generated by Django 5.2.7 on 2026-06-29 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
        ('store', '0006_remove_produit_status_alter_produit_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], db_index=True, default='image', max_length=20)),
                ('position', models.CharField(choices=[('grande_banniere', 'Grande bannière accueil'), ('nouveau_arrivage', 'Bannière nouveau arrivage'), ('banniere_video', 'Bannière vidéo'), ('promotion', 'Bannière promotion')], db_index=True, default='grande_banniere', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecommerce/banners/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ecommerce/banners/videos/')),
                ('lien_action', models.URLField(blank=True, null=True)),
                ('texte_bouton', models.CharField(blank=True, max_length=80, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='livraisonecommerce',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commandeecommerce',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paiementecommerce',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='EcommerceHomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('featured', 'Produits sélectionnés'), ('new_arrival', 'Nouveaux arrivages'), ('slider', 'Carrousel'), ('best_seller', 'Meilleures ventes')], db_index=True, default='featured', max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('titre_personnalise', models.CharField(blank=True, max_length=150, null=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('image_personnalisee', models.ImageField(blank=True, null=True, upload_to='ecommerce/home/products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bijouterie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_ecommerce_products', to='store.bijouterie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_ecommerce_items', to='store.produit')),
            ],
            options={
                'ordering': ['section', 'ordre_affichage', '-created_at'],
                'indexes': [models.Index(fields=['section', 'active'], name='e_commerce__section_66f726_idx')],
                'constraints': [models.UniqueConstraint(fields=('produit', 'bijouterie', 'section'), name='uniq_home_product_by_shop_section')],
            },
        ),
    ]
