# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commerce', '0002_initial'),
        ('purchase', '0002_initial'),
        ('sale', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeecommerce',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_ecommerce_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandeecommerce',
            name='facture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_ecommerce', to='sale.facture'),
        ),
        migrations.AddField(
            model_name='commandeecommerce',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_ecommerce', to='sale.vente'),
        ),
        migrations.AddField(
            model_name='commandeecommerceligne',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='e_commerce.commandeecommerce'),
        ),
        migrations.AddField(
            model_name='commandeecommerceligne',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecommerce', to='store.produit'),
        ),
        migrations.AddField(
            model_name='commandeecommerceligne',
            name='produit_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecommerce', to='purchase.produitline'),
        ),
        migrations.AddField(
            model_name='ecommercehomeproduit',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_ecommerce_produits', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='ecommercehomeproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_ecommerce_items', to='store.produit'),
        ),
        migrations.AddField(
            model_name='livraisonecommerce',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='e_commerce.commandeecommerce'),
        ),
        migrations.AddField(
            model_name='paiementecommerce',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='e_commerce.commandeecommerce'),
        ),
        migrations.AddIndex(
            model_name='ecommercehomeproduit',
            index=models.Index(fields=['section', 'active'], name='e_commerce__section_66f726_idx'),
        ),
        migrations.AddConstraint(
            model_name='ecommercehomeproduit',
            constraint=models.UniqueConstraint(fields=('produit', 'bijouterie', 'section'), name='uniq_home_produit_by_shop_section'),
        ),
    ]
