# Generated by Django 5.2.7 on 2026-08-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeecommerce',
            name='bijouterie',
        ),
        migrations.RemoveField(
            model_name='commandeecommerce',
            name='client',
        ),
        migrations.RemoveField(
            model_name='commandeecommerce',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='commandeecommerce',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='commandeecommerce',
            name='vente',
        ),
        migrations.RemoveField(
            model_name='paiementecommerce',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='livraisonecommerce',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='commandeecommerceligne',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='commandeecommerceligne',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commandeecommerceligne',
            name='produit_line',
        ),
        migrations.DeleteModel(
            name='EcommerceBanner',
        ),
        migrations.RemoveField(
            model_name='ecommercehomeproduct',
            name='bijouterie',
        ),
        migrations.RemoveField(
            model_name='ecommercehomeproduct',
            name='produit',
        ),
        migrations.DeleteModel(
            name='PaiementEcommerce',
        ),
        migrations.DeleteModel(
            name='LivraisonEcommerce',
        ),
        migrations.DeleteModel(
            name='CommandeEcommerce',
        ),
        migrations.DeleteModel(
            name='CommandeEcommerceLigne',
        ),
        migrations.DeleteModel(
            name='EcommerceHomeProduct',
        ),
    ]
