# Generated by Django 5.2.7 on 2026-09-23 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeecommerceligne',
            name='quantite',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
