# Generated by Django 5.2.5 on 2025-10-22 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('template', models.CharField(max_length=100)),
                ('context', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('next_try_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['next_try_at', 'to'], name='userauths_o_next_tr_b9576c_idx')],
            },
        ),
    ]
