# Generated by Django 5.1.3 on 2025-01-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_bijouterie_options_and_more'),
        ('userauths', '0002_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bijouterie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bijouterie', to='store.bijouterie'),
        ),
    ]
