# Generated by Django 5.2.5 on 2025-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('is_reserved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
