# Generated by Django 5.2.5 on 2025-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reserved', models.BooleanField(default=True, help_text='True = non attribué à une bijouterie')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('reservation_key', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-id'],
            },
        ),
    ]
