# Generated by Django 5.2.5 on 2025-10-08 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('stock', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='stock',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='purchase.achatproduitlot'),
        ),
        migrations.AddField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='store.produit'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['produit', 'bijouterie'], name='stock_stock_produit_b4b3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['lot'], name='stock_stock_lot_id_045d86_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_reserved'], name='stock_stock_is_rese_b24ce5_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('produit', 'bijouterie', 'lot'), name='uniq_stock_prod_bij_lot'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint = models.CheckConstraint(check=models.Q(quantite__gte=0),name='ck_stock_quantite_gte_0',)
        ),
    ]
