# Generated by Django 5.2.7 on 2026-04-22 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstock',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='vendor.vendor'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reserve', True)), fields=('produit_line',), name='uq_stock_one_reserve_per_pl'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reserve', False)), fields=('produit_line', 'bijouterie'), name='uq_stock_pl_bijouterie_non_reserve'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bijouterie__isnull', True), ('is_reserve', True)), models.Q(('bijouterie__isnull', False), ('is_reserve', False)), _connector='OR'), name='ck_stock_is_reserve_matches_bijouterie_null'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_totale__gte', models.F('en_stock'))), name='ck_stock_en_stock_lte_quantite_totale'),
        ),
        migrations.AddIndex(
            model_name='vendorstock',
            index=models.Index(fields=['vendor', 'bijouterie'], name='stock_vendo_vendor__b20e51_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorstock',
            index=models.Index(fields=['vendor', 'produit_line'], name='stock_vendo_vendor__7e9108_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorstock',
            index=models.Index(fields=['bijouterie', 'produit_line'], name='stock_vendo_bijoute_0674ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorstock',
            constraint=models.UniqueConstraint(fields=('produit_line', 'vendor', 'bijouterie'), name='uq_vendorstock_pl_vendor_bij'),
        ),
        migrations.AddConstraint(
            model_name='vendorstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_allouee__gte', 0), ('quantite_vendue__gte', 0), ('quantite_vendue__lte', models.F('quantite_allouee'))), name='ck_vendorstock_valid_quantities'),
        ),
    ]
