# Generated by Django 5.2.7 on 2025-11-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstock',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['bijouterie'], name='stock_stock_bijoute_17bd28_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['produit_line', 'bijouterie'], name='stock_stock_produit_580ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('produit_line', 'bijouterie'), name='uq_stock_pl_bijouterie'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantite_allouee__isnull', True), ('quantite_disponible__isnull', True)), ('quantite_allouee__gte', models.F('quantite_disponible')), _connector='OR'), name='ck_stock_qty_disp_lte_alloue'),
        ),
        migrations.AddIndex(
            model_name='vendorstock',
            index=models.Index(fields=['vendor'], name='stock_vendo_vendor__29da1c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorstock',
            index=models.Index(fields=['produit_line'], name='stock_vendo_produit_43995c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorstock',
            constraint=models.UniqueConstraint(fields=('produit_line', 'vendor'), name='uq_vendorstock_pl_vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendorstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_allouee__gte', 0), ('quantite_vendue__gte', 0), ('quantite_vendue__lte', models.F('quantite_allouee'))), name='ck_vendorstock_nonneg_and_vendue_lte_allouee'),
        ),
    ]
