# Generated by Django 5.2.5 on 2025-09-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_achatproduitlot_alter_achat_options_and_more'),
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='purchase.achatproduitlot'),
        ),
    ]
