# # Generated by Django 5.2.5 on 2025-10-14 00:54

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('purchase', '0002_initial'),
#         ('stock', '0002_initial'),
#         ('store', '0002_initial'),
#     ]

#     operations = [
#         migrations.RemoveConstraint(
#             model_name='stock',
#             name='ck_stock_qty_gte_0',
#         ),
#         migrations.RemoveConstraint(
#             model_name='stock',
#             name='ck_stock_weight_gte_0',
#         ),
#         migrations.RemoveConstraint(
#             model_name='stock',
#             name='ck_stock_has_qty_or_weight',
#         ),
#         migrations.RemoveConstraint(
#             model_name='stock',
#             name='ck_stock_qty_xor_weight',
#         ),
#         migrations.RemoveField(
#             model_name='stock',
#             name='poids_grammes',
#         ),
#         migrations.AlterField(
#             model_name='stock',
#             name='reservation_key',
#             field=models.CharField(blank=True, max_length=64, null=True),
#         ),
#         migrations.AddConstraint(
#             model_name='stock',
#             constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='ck_stock_qty_gt_0'),
#         ),
#         migrations.AddConstraint(
#             model_name='stock',
#             constraint=models.UniqueConstraint(condition=models.Q(('is_reserved', True)), fields=('reservation_key',), name='uniq_reservation_key_when_reserved'),
#         ),
#     ]

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
        ('stock', '0002_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='ck_stock_qty_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='ck_stock_weight_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='ck_stock_has_qty_or_weight',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='ck_stock_qty_xor_weight',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='poids_grammes',
        ),
        migrations.AlterField(
            model_name='stock',
            name='reservation_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        # ✅ quantité strictement > 0
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(
                check=Q(quantite__gt=0),
                name='ck_stock_qty_gt_0',
            ),
        ),
        # ✅ unicité conditionnelle quand réservé ET reservation_key non NULL
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(
                fields=('reservation_key',),
                condition=Q(is_reserved=True, reservation_key__isnull=False),
                name='uniq_reservation_key_when_reserved',
            ),
        ),
    ]