# Generated by Django 5.2.7 on 2026-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='uq_stock_one_reserve_per_pl',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='uq_stock_pl_bijouterie_non_reserve',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
