# Generated by Django 5.2.5 on 2025-10-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
        ('stock', '0003_remove_stock_ck_stock_qty_gte_0_and_more'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='uniq_reservation_key_when_reserved',
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reserved', True)), fields=('reservation_key',), name='uniq_reservation_key_when_reserved'),
        ),
    ]
