# Generated by Django 5.2.5 on 2025-09-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_achatproduitlot_alter_achat_options_and_more'),
        ('stock', '0003_stock_lot'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='uniq_stock_produit_bijouterie',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_stock_produit_c3e5a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_stock_bijoute_17bd28_idx',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_modification',
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_reserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='purchase.achatproduitlot'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reservation_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['produit', 'bijouterie'], name='stock_stock_produit_b4b3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['lot'], name='stock_stock_lot_id_045d86_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('produit', 'bijouterie', 'lot'), name='uniq_stock_prod_bij_lot'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(
            check=models.Q(quantite__gte=0),        # ✅ bon param et syntaxe plus lisible
            name='stock_qty_gte_0',
        ),
),
    ]
