# Generated by Django 5.1.3 on 2024-12-29 15:18

import django.db.models.deletion
import shortuuid.django_fields
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bijouterie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True, unique=True)),
                ('telephone_portable', models.CharField(max_length=30, null=True, unique=True)),
                ('telephone_fix', models.CharField(max_length=30, null=True, unique=True)),
                ('adresse', models.CharField(max_length=30, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='logo/')),
                ('tiktok', models.CharField(max_length=30, null=True, unique=True)),
                ('facebook', models.CharField(max_length=30, null=True, unique=True)),
                ('intagram', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='category.jpg', null=True, unique=True, upload_to='categorie/')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Marques',
            },
        ),
        migrations.CreateModel(
            name='Purete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purete', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=55, null=True, unique=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_categorie', to='store.categorie')),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='produits/')),
                ('description', models.TextField(blank=True, null=True)),
                ('matiere', models.CharField(blank=True, choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=50, null=True)),
                ('poids', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('genre', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('enfant', 'Enfant')], default='femme', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('désactivé', 'Désactivé'), ('rejetée', 'Rejetée'), ('en_revue', 'En Revue'), ('publié', 'Publié')], default='publié', max_length=50, null=True)),
                ('prix_vente_grammes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('prix_avec_tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('quantite_en_stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_produit', to='store.categorie')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marque_produit', to='store.marque')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_produit', to='store.modele')),
                ('purete', models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purete_produit', to='store.purete')),
            ],
            options={
                'verbose_name_plural': 'Produits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='gallery.jpg', upload_to='gallery/')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=22, max_length=25, prefix='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_gallery', to='store.produit')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='marque',
            name='purete',
            field=models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purete_marque', to='store.purete'),
        ),
    ]
