# Generated by Django 4.2 on 2025-08-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modele',
            options={},
        ),
        migrations.AddField(
            model_name='modele',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_categorie', to='store.categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='matiere',
            field=models.CharField(blank=True, choices=[('or', 'Or'), ('ar', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purete',
            name='purete',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='CategorieModele',
        ),
    ]
