# Generated by Django 5.2.5 on 2025-10-08 09:20

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='modifier_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modele',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_categorie', to='store.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_produit', to='store.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marque_produit', to='store.marque'),
        ),
        migrations.AddField(
            model_name='produit',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_produit', to='store.modele'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_gallery', to='store.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='purete',
            field=models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purete_produit', to='store.purete'),
        ),
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.purete'),
        ),
        migrations.AddField(
            model_name='marquepurete',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purete_marques', to='store.purete'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['marque', 'purete', 'date_modification'], name='store_marqu_marque__29e5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepurete',
            index=models.Index(fields=['marque', 'purete'], name='store_marqu_marque__72ed49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marquepurete',
            unique_together={('marque', 'purete')},
        ),
    ]
