# Generated by Django 4.2 on 2025-05-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modele',
            options={},
        ),
    ]
