# Generated by Django 5.1.3 on 2025-01-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bijouterie',
            options={'verbose_name_plural': 'Bijouteries'},
        ),
        migrations.RenameField(
            model_name='bijouterie',
            old_name='telephone_portable',
            new_name='nom_de_domaine',
        ),
        migrations.RemoveField(
            model_name='bijouterie',
            name='logo',
        ),
        migrations.AddField(
            model_name='bijouterie',
            name='logo_blanc',
            field=models.ImageField(blank=True, default='logo_blanc.jpg', null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='bijouterie',
            name='logo_noir',
            field=models.ImageField(blank=True, default='logo_noir.jpg', null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='bijouterie',
            name='telephone_portable_1',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bijouterie',
            name='telephone_portable_2',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bijouterie',
            name='telephone_portable_3',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bijouterie',
            name='telephone_portable_4',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bijouterie',
            name='telephone_portable_5',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
