# Generated by Django 5.2.7 on 2026-04-22 23:22

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_prix_marque_purete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiques_prix', to='store.marque'),
        ),
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='marque_purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_prix', to='store.marquepurete'),
        ),
        migrations.AddField(
            model_name='modele',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_categorie', to='store.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_produit', to='store.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marque_produit', to='store.marque'),
        ),
        migrations.AddField(
            model_name='produit',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_produit', to='store.modele'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_gallery', to='store.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='purete',
            field=models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purete_produit', to='store.purete'),
        ),
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiques_prix', to='store.purete'),
        ),
        migrations.AddField(
            model_name='marquepurete',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purete_marques', to='store.purete'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['changed_at'], name='store_marqu_changed_68d267_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['marque_purete', 'changed_at'], name='store_marqu_marque__050505_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['marque', 'purete'], name='store_marqu_marque__dc1593_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['bijouterie'], name='store_marqu_bijoute_ec7ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['source'], name='store_marqu_source_efbd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['changed_by'], name='store_marqu_changed_b7044a_idx'),
        ),
        migrations.AddConstraint(
            model_name='marquepureteprixhistory',
            constraint=models.CheckConstraint(condition=models.Q(('ancien_prix__gte', 0)), name='mph_ancien_prix_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='marquepureteprixhistory',
            constraint=models.CheckConstraint(condition=models.Q(('nouveau_prix__gte', 0)), name='mph_nouveau_prix_gte_0'),
        ),
        migrations.AddIndex(
            model_name='marquepurete',
            index=models.Index(fields=['marque', 'purete'], name='store_marqu_marque__72ed49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marquepurete',
            unique_together={('marque', 'purete')},
        ),
    ]
