# Generated by Django 5.1.3 on 2025-06-22 20:05

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modele',
            name='categorie',
        ),
        migrations.AddField(
            model_name='marque',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marques_categorie', to='store.categorie'),
        ),
        migrations.AddField(
            model_name='modele',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele_marque', to='store.marque'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='purete',
            field=models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marques_purete', to='store.purete'),
        ),
    ]
