# Generated by Django 4.2 on 2025-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Galerie'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gid',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='produit_gallery/'),
        ),
    ]
