# Generated by Django 4.2 on 2025-08-17 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='modifier_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marquepureteprixhistory',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.purete'),
        ),
        migrations.AddField(
            model_name='marquepurete',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marque_puretes', to='store.marque'),
        ),
        migrations.AddField(
            model_name='marquepurete',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purete_marques', to='store.purete'),
        ),
        migrations.AddField(
            model_name='historiqueprix',
            name='marque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.marque'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_gallery', to='store.produit'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['marque', 'purete', 'date_modification'], name='store_marqu_marque__29e5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepurete',
            index=models.Index(fields=['marque', 'purete'], name='store_marqu_marque__72ed49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marquepurete',
            unique_together={('marque', 'purete')},
        ),
    ]
