# Generated by Django 4.2 on 2025-05-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modele',
            options={},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='purete',
            name='purete',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
