# Generated by Django 5.2.7 on 2026-08-17 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_gallery', to='store.produit'),
        ),
        migrations.AlterField(
            model_name='marquepureteprixhistory',
            name='modifier_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changements_prix_marque_purete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modele',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modele_categorie', to='store.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorie_produit', to='store.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('N', 'Neuf'), ('O', 'Occasion')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant'), ('U', 'Unisexe')], default='F', max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marque_produit', to='store.marque'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modele_produit', to='store.modele'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='poids',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='produit',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purete_produit', to='store.purete'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
