# Generated by Django 4.2 on 2025-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_modele_options_remove_produit_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
