# Generated by Django 5.2.7 on 2026-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijouterie',
            name='appliquer_tva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bijouterie',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
