# Generated by Django 4.2 on 2025-08-08 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_modele_options_modele_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marquepurete',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 8, 14, 41, 35, 309866, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marquepurete',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='marquepurete',
            index=models.Index(fields=['marque', 'purete'], name='store_marqu_marque__72ed49_idx'),
        ),
    ]
