# Generated by Django 5.2.7 on 2026-08-27 01:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_gallery_active_alter_gallery_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pourcentage_occasion',
            field=models.DecimalField(blank=True, choices=[(Decimal('5.00'), '5%'), (Decimal('10.00'), '10%'), (Decimal('15.00'), '15%'), (Decimal('20.00'), '20%')], decimal_places=2, help_text="Réduction appliquée uniquement aux produits d'occasion.", max_digits=5, null=True),
        ),
    ]
