# Generated by Django 4.2 on 2025-05-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_produit_qr_code_alter_purete_purete'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
