# Generated by Django 4.2 on 2025-08-09 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_marquepurete_date_ajout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarquePuretePrixHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nouveau_prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.marque')),
                ('modifier_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.purete')),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['marque', 'purete', 'date_modification'], name='store_marqu_marque__29e5a5_idx'),
        ),
    ]
