# Generated by Django 5.2.7 on 2026-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_bijouterie_appliquer_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='matiere',
            field=models.CharField(blank=True, choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=50, null=True),
        ),
    ]
