# Generated by Django 5.2.7 on 2026-06-06 03:02

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_produit_matiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marquepureteprixhistory',
            options={'ordering': ['-date_modification', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='marquepureteprixhistory',
            name='store_marqu_changed_68d267_idx',
        ),
        migrations.RemoveIndex(
            model_name='marquepureteprixhistory',
            name='store_marqu_marque__050505_idx',
        ),
        migrations.RemoveIndex(
            model_name='marquepureteprixhistory',
            name='store_marqu_changed_b7044a_idx',
        ),
        migrations.RenameField(
            model_name='marquepureteprixhistory',
            old_name='changed_at',
            new_name='date_modification',
        ),
        migrations.RenameField(
            model_name='marquepureteprixhistory',
            old_name='changed_by',
            new_name='modifier_par',
        ),
        migrations.AddField(
            model_name='produit',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['date_modification'], name='store_marqu_date_mo_6ccc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['marque_purete', 'date_modification'], name='store_marqu_marque__e2ce04_idx'),
        ),
        migrations.AddIndex(
            model_name='marquepureteprixhistory',
            index=models.Index(fields=['modifier_par'], name='store_marqu_modifie_ea68a8_idx'),
        ),
    ]
