# Generated by Django 5.2.7 on 2026-09-02 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_produit_pourcentage_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorie_produit', to='store.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marque_produit', to='store.marque'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purete_produit', to='store.purete'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
