# Generated by Django 5.2.7 on 2026-06-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_marquepureteprixhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='status',
        ),
        migrations.AlterField(
            model_name='produit',
            name='etat',
            field=models.CharField(blank=True, choices=[('N', 'Neuf'), ('O', 'Occasion')], default='N', max_length=10, null=True),
        ),
    ]
