# Generated by Django 5.2.7 on 2026-10-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_produit_categorie_alter_produit_marque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='pourcentage_occasion',
            new_name='reduction_occasion',
        ),
    ]
