# Generated by Django 5.2.7 on 2026-07-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_produit_status_alter_produit_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='genre',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant'), ('U', 'Unisexe')], default='F', max_length=10, null=True),
        ),
    ]
