# Generated by Django 5.2.7 on 2026-08-06 21:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(choices=[('salaire', 'Salaire'), ('loyer', 'Loyer'), ('transport', 'Transport'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('internet', 'Internet'), ('fourniture', 'Fourniture'), ('reparation', 'Réparation'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('beneficiaire', models.CharField(blank=True, max_length=150, null=True)),
                ('telephone_beneficiaire', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
