# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_payees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_modifiees', to=settings.AUTH_USER_MODEL),
        ),
    ]
