# Generated by Django 5.2.7 on 2026-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifie', models.BooleanField(db_index=True, default=True)),
                ('raison_desactivation', models.TextField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Responsable rachat',
                'verbose_name_plural': 'Responsables rachats',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifie', models.BooleanField(db_index=True, default=True)),
                ('raison_desactivation', models.TextField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caissier',
                'verbose_name_plural': 'Caissiers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifie', models.BooleanField(db_index=True, default=True)),
                ('raison_desactivation', models.TextField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'ordering': ['-id'],
            },
        ),
    ]
