# Generated by Django 4.2 on 2025-09-27 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cashier',
            name='staff_cashier_verifie_idx',
        ),
        migrations.AddField(
            model_name='cashier',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashiers', related_query_name='cashier', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cashier_profile', related_query_name='cashier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='verifie',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
