# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='desactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desactives', related_query_name='%(app_label)s_%(class)s_desactive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_buyer_profile', related_query_name='buyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashier',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashiers', related_query_name='cashier', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='desactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desactives', related_query_name='%(app_label)s_%(class)s_desactive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_cashier_profile', related_query_name='cashier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='bijouteries',
            field=models.ManyToManyField(blank=True, related_name='managers', related_query_name='manager', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='manager',
            name='desactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desactives', related_query_name='%(app_label)s_%(class)s_desactive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_manager_profile', related_query_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='buyer',
            index=models.Index(fields=['bijouterie', 'verifie'], name='idx_buyer_bij_verif'),
        ),
        migrations.AddIndex(
            model_name='cashier',
            index=models.Index(fields=['bijouterie', 'verifie'], name='idx_cashier_bij_verif'),
        ),
    ]
