# Generated by Django 5.2.5 on 2025-10-08 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_cashier_profile', related_query_name='cashier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', related_query_name='manager', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_manager_profile', related_query_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['verifie'], name='staff_manag_verifie_a01a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['bijouterie'], name='staff_manag_bijoute_671d91_idx'),
        ),
    ]
