# Generated by Django 5.2.7 on 2026-07-05 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_initial'),
        ('store', '0007_alter_produit_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='desactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desactives', related_query_name='%(app_label)s_%(class)s_desactive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='desactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desactives', related_query_name='%(app_label)s_%(class)s_desactive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifie', models.BooleanField(db_index=True, default=True)),
                ('raison_desactivation', models.TextField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='store.bijouterie')),
                ('desactive_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_desactives', related_query_name='%(app_label)s_%(class)s_desactive', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acheteur',
                'verbose_name_plural': 'Acheteurs',
            },
        ),
    ]
