# Generated by Django 5.2.7 on 2026-10-07 11:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction_produit_occasion', models.DecimalField(choices=[(Decimal('5.00'), '5 %'), (Decimal('10.00'), '10 %'), (Decimal('15.00'), '15 %'), (Decimal('20.00'), '20 %')], decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre commercial',
                'verbose_name_plural': 'Paramètres commerciaux',
            },
        ),
    ]
