# Generated by Django 5.2.7 on 2026-10-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialsettings',
            name='bijouterie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_settings', to='store.bijouterie'),
        ),
    ]
