# Generated by Django 4.2 on 2025-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shop Name', max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='user-images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
