<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-03 09:47
=======
# Generated by Django 4.2 on 2025-08-25 09:14
>>>>>>> 949a9334 (en cours avant merge)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='store.bijouterie'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='employee_em_phone_3f029b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['active'], name='employee_em_active_0c5167_idx'),
        ),
    ]
