# Generated by Django 5.2.5 on 2025-09-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='store.bijouterie'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='employee_em_phone_3f029b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['active'], name='employee_em_active_0c5167_idx'),
        ),
    ]
