# Generated by Django 5.2.7 on 2025-11-02 13:30

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Note interne (motif, consignes, etc.)', null=True)),
                ('frais_transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('frais_douane', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('numero_achat', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('montant_total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='confirmed', max_length=20)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProduitLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_gramme_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantite_total', models.PositiveIntegerField()),
                ('quantite_restante', models.PositiveIntegerField()),
            ],
        ),
    ]
