<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-03 09:47
=======
# Generated by Django 4.2 on 2025-08-25 09:14
>>>>>>> 949a9334 (en cours avant merge)

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant_total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('montant_total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AchatProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_achat_produit', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('quantite', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_achat_gramme', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('sous_total_prix_achat', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='purchase.achat')),
            ],
            options={
                'verbose_name': 'Produit acheté',
                'verbose_name_plural': 'Produits achetés',
            },
        ),
    ]
