# Generated by Django 5.2.5 on 2025-09-14 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achatproduit',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='purchase.achat'),
        ),
        migrations.AddField(
            model_name='achatproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_produits', to='store.produit'),
        ),
        migrations.AddField(
            model_name='achatproduit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.fournisseur'),
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', related_query_name='achat', to='purchase.fournisseur'),
        ),
        migrations.AddIndex(
            model_name='achatproduit',
            index=models.Index(fields=['achat'], name='purchase_ac_achat_i_a46d36_idx'),
        ),
        migrations.AddIndex(
            model_name='achatproduit',
            index=models.Index(fields=['produit'], name='purchase_ac_produit_e92b56_idx'),
        ),
        migrations.AddIndex(
            model_name='achatproduit',
            index=models.Index(fields=['numero_achat_produit'], name='purchase_ac_numero__c6efcd_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['created_at'], name='purchase_ac_created_eb51f5_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['fournisseur'], name='purchase_ac_fournis_3de7d7_idx'),
        ),
    ]
