# Generated by Django 4.2 on 2025-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatproduit',
            name='numero_achat_produit',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
