# Generated by Django 5.2.5 on 2025-10-20 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', related_query_name='achat', to='purchase.fournisseur'),
        ),
        migrations.AddField(
            model_name='lot',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='purchase.achat'),
        ),
        migrations.AddField(
            model_name='produitline',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='purchase.lot'),
        ),
        migrations.AddField(
            model_name='produitline',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produit_lines', to='store.produit'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['created_at'], name='purchase_ac_created_eb51f5_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['fournisseur'], name='purchase_ac_fournis_3de7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['status'], name='purchase_ac_status_c072ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(condition=models.Q(('frais_transport__gte', 0)), name='achat_frais_transport_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(condition=models.Q(('frais_douane__gte', 0)), name='achat_frais_douane_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total_ht__gte', 0)), name='achat_ht_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total_ttc__gte', 0)), name='achat_ttc_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total_ttc__gte', models.F('montant_total_ht'))), name='achat_ttc_gte_ht'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled')), models.Q(('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'confirmed')), _connector='OR'), name='achat_cancel_fields_consistency'),
        ),
        migrations.AddIndex(
            model_name='produitline',
            index=models.Index(fields=['lot'], name='purchase_pr_lot_id_6d5c16_idx'),
        ),
        migrations.AddIndex(
            model_name='produitline',
            index=models.Index(fields=['produit'], name='purchase_pr_produit_719659_idx'),
        ),
        migrations.AddConstraint(
            model_name='produitline',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_total__gte', 1)), name='ck_pl_qty_gte1'),
        ),
        migrations.AddConstraint(
            model_name='produitline',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_restante__gte', 0)), name='ck_pl_qtyrest_gte0'),
        ),
    ]
