# Generated by Django 4.2 on 2025-10-05 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', related_query_name='achat', to='purchase.fournisseur'),
        ),
        migrations.AddIndex(
            model_name='achatproduitlot',
            index=models.Index(fields=['date_reception'], name='purchase_ac_date_re_8a9c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='achatproduitlot',
            index=models.Index(fields=['achat_ligne', 'date_reception'], name='purchase_ac_achat_l_617e56_idx'),
        ),
        migrations.AddIndex(
            model_name='achatproduitlot',
            index=models.Index(fields=['quantite_restante'], name='purchase_ac_quantit_97890d_idx'),
        ),
        migrations.AddConstraint(
            model_name='achatproduitlot',
            constraint=models.CheckConstraint(check=models.Q(('quantite_total__gt', 0)), name='lot_quantite_total_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='achatproduitlot',
            constraint=models.CheckConstraint(check=models.Q(('quantite_restante__gte', 0)), name='lot_quantite_restante_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achatproduitlot',
            constraint=models.CheckConstraint(check=models.Q(('quantite_restante__lte', models.F('quantite_total'))), name='lot_quantite_restante_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='achatproduitlot',
            constraint=models.CheckConstraint(check=models.Q(('prix_achat_gramme__gte', 0)), name='lot_prix_achat_gramme_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achatproduitlot',
            constraint=models.CheckConstraint(check=models.Q(('date_peremption__isnull', True), ('date_peremption__gte', models.F('date_reception')), _connector='OR'), name='lot_peremption_after_or_null'),
        ),
        migrations.AddIndex(
            model_name='achatproduit',
            index=models.Index(fields=['achat'], name='purchase_ac_achat_i_a46d36_idx'),
        ),
        migrations.AddIndex(
            model_name='achatproduit',
            index=models.Index(fields=['produit'], name='purchase_ac_produit_e92b56_idx'),
        ),
        migrations.AddIndex(
            model_name='achatproduit',
            index=models.Index(fields=['lot_code'], name='purchase_ac_lot_cod_5bdf65_idx'),
        ),
        migrations.AddConstraint(
            model_name='achatproduit',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0)), name='achatprod_tax_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achatproduit',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', 0)), name='achatprod_tax_amount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['created_at'], name='purchase_ac_created_eb51f5_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['fournisseur'], name='purchase_ac_fournis_3de7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='achat',
            index=models.Index(fields=['status'], name='purchase_ac_status_c072ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(check=models.Q(('montant_total_ht__gte', 0)), name='achat_ht_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(check=models.Q(('montant_total_ttc__gte', 0)), name='achat_ttc_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(check=models.Q(('montant_total_ttc__gte', models.F('montant_total_ht'))), name='achat_ttc_gte_ht'),
        ),
        migrations.AddConstraint(
            model_name='achat',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled')), models.Q(('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'confirmed')), _connector='OR'), name='achat_cancel_fields_consistency'),
        ),
    ]
