# Generated by Django 5.2.7 on 2026-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_initial'),
        ('store', '0005_alter_produit_categorie_alter_produit_marque_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitline',
            options={'ordering': ['lot_id', 'numero_ligne_lot', 'id']},
        ),
        migrations.RenameIndex(
            model_name='produitline',
            new_name='idx_pl_lot',
            old_name='purchase_pr_lot_id_6d5c16_idx',
        ),
        migrations.RenameIndex(
            model_name='produitline',
            new_name='idx_pl_produit',
            old_name='purchase_pr_produit_719659_idx',
        ),
        migrations.AddField(
            model_name='produitline',
            name='numero_ligne_lot',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='produitline',
            index=models.Index(fields=['lot', 'numero_ligne_lot'], name='idx_pl_lot_numero'),
        ),
        migrations.AddConstraint(
            model_name='produitline',
            constraint=models.UniqueConstraint(fields=('lot', 'numero_ligne_lot'), name='unique_numero_ligne_par_lot'),
        ),
    ]
