# Generated by Django 5.2.5 on 2025-09-14 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Entrée achat'), ('CANCEL_PURCHASE', 'Annulation achat (sortie)'), ('ALLOCATE', 'Affectation réservé → bijouterie'), ('TRANSFER', 'Transfert entre bijouteries'), ('ADJUSTMENT', 'Ajustement manuel'), ('SALE_OUT', 'Sortie vente'), ('RETURN_IN', 'Retour client (entrée)')], max_length=32)),
                ('qty', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('src_bucket', models.CharField(blank=True, choices=[('EXTERNAL', 'Externe (hors système)'), ('RESERVED', 'Réservé (bijouterie=NULL)'), ('BIJOUTERIE', 'Bijouterie')], max_length=16, null=True)),
                ('dst_bucket', models.CharField(blank=True, choices=[('EXTERNAL', 'Externe (hors système)'), ('RESERVED', 'Réservé (bijouterie=NULL)'), ('BIJOUTERIE', 'Bijouterie')], max_length=16, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Mouvement d'inventaire",
                'verbose_name_plural': "Mouvements d'inventaire",
                'ordering': ['-id'],
            },
        ),
    ]
