# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Entrée fournisseur'), ('RETURN_IN', 'Retour client'), ('SALE_OUT', 'Vente'), ('VENDOR_ASSIGN', 'Affectation vendeur'), ('CANCEL_PURCHASE', 'Annulation achat'), ('ADJUSTMENT', 'Ajustement manuel')], db_index=True, max_length=32)),
                ('qty', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('src_bucket', models.CharField(blank=True, choices=[('EXTERNAL', 'Externe'), ('BIJOUTERIE', 'Bijouterie'), ('VENDOR', 'Vendeur')], max_length=16, null=True)),
                ('dst_bucket', models.CharField(blank=True, choices=[('EXTERNAL', 'Externe'), ('BIJOUTERIE', 'Bijouterie'), ('VENDOR', 'Vendeur')], max_length=16, null=True)),
                ('stock_consumed', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
