# Generated by Django 5.2.7 on 2025-11-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='purchase.achat'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='achat_ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='purchase.lot'),
        ),
    ]
