# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchase', '0002_initial'),
        ('sale', '0002_initial'),
        ('store', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='dst_bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_as_destination', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='sale.facture'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='purchase.lot'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.produit'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='produit_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='purchase.produitline'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='src_bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_as_source', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='sale.vente'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='vente_ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='sale.venteproduit'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'occurred_at'], name='inv_mov_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['facture'], name='inv_mov_facture_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['vente'], name='inv_mov_vente_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['produit', 'occurred_at'], name='inv_mov_produit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['src_bijouterie'], name='inv_mov_src_shop_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['dst_bijouterie'], name='inv_mov_dst_shop_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['vendor', 'occurred_at'], name='inv_mov_vendor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'vendor'], name='inv_mov_type_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['vente_ligne', 'movement_type'], name='inv_mov_sale_line_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['produit_line', 'movement_type'], name='inv_mov_pline_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='inv_move_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('src_bucket', 'BIJOUTERIE'), _negated=True), ('src_bijouterie_id__isnull', False), _connector='OR'), name='inv_move_src_bijouterie_required'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dst_bucket', 'BIJOUTERIE'), _negated=True), ('dst_bijouterie_id__isnull', False), _connector='OR'), name='inv_move_dst_bijouterie_required'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'PURCHASE_IN'), _negated=True), models.Q(('src_bucket', 'EXTERNAL'), ('dst_bucket', 'BIJOUTERIE'), ('dst_bijouterie_id__isnull', False), ('produit_line_id__isnull', False), ('lot_id__isnull', False)), _connector='OR'), name='ck_purchase_in_external_to_shop'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'VENDOR_ASSIGN'), _negated=True), models.Q(('src_bucket', 'BIJOUTERIE'), ('dst_bucket', 'VENDOR'), ('src_bijouterie_id__isnull', False), ('dst_bijouterie_id__isnull', False), ('vendor_id__isnull', False), ('produit_line_id__isnull', False), ('lot_id__isnull', False)), _connector='OR'), name='ck_vendor_assign_shop_to_vendor'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'SALE_OUT'), _negated=True), models.Q(('src_bucket', 'VENDOR'), ('dst_bucket', 'EXTERNAL'), ('vendor_id__isnull', False), ('vente_id__isnull', False), ('vente_ligne_id__isnull', False), ('produit_line_id__isnull', False)), _connector='OR'), name='ck_sale_out_vendor_to_external'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'RETURN_IN'), _negated=True), models.Q(('src_bucket', 'EXTERNAL'), ('dst_bucket', 'BIJOUTERIE'), ('dst_bijouterie_id__isnull', False), ('vente_id__isnull', False), ('vente_ligne_id__isnull', False), ('produit_line_id__isnull', False)), _connector='OR'), name='ck_return_in_external_to_shop'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'CANCEL_PURCHASE'), _negated=True), models.Q(('src_bucket', 'BIJOUTERIE'), ('dst_bucket', 'EXTERNAL'), ('src_bijouterie_id__isnull', False), ('produit_line_id__isnull', False)), _connector='OR'), name='ck_cancel_purchase_shop_to_external'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'ADJUSTMENT'), _negated=True), models.Q(('src_bucket', 'EXTERNAL'), ('dst_bucket', 'BIJOUTERIE'), ('dst_bijouterie_id__isnull', False)), models.Q(('src_bucket', 'BIJOUTERIE'), ('dst_bucket', 'EXTERNAL'), ('src_bijouterie_id__isnull', False)), _connector='OR'), name='ck_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type', 'SALE_OUT')), fields=('vente_ligne', 'produit_line'), name='uniq_sale_out_per_sale_line_produit_line'),
        ),
    ]
