# Generated by Django 4.2 on 2025-09-27 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('store', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='dst_bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_as_destination', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.achatproduitlot'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.produit'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='src_bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_as_source', to='store.bijouterie'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(check=models.Q(('qty__gt', 0)), name='inv_move_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('src_bucket', 'BIJOUTERIE'), _negated=True), ('src_bijouterie__isnull', False), _connector='OR'), name='inv_move_src_bijouterie_required_when_src_bucket_is_shop'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('dst_bucket', 'BIJOUTERIE'), _negated=True), ('dst_bijouterie__isnull', False), _connector='OR'), name='inv_move_dst_bijouterie_required_when_dst_bucket_is_shop'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('movement_type', 'TRANSFER'), _negated=True), models.Q(('dst_bucket', 'BIJOUTERIE'), ('src_bucket', 'BIJOUTERIE'), models.Q(('src_bijouterie', models.F('dst_bijouterie')), _negated=True)), _connector='OR'), name='inv_move_transfer_src_dst_must_differ'),
        ),
    ]
