# Generated by Django 4.2 on 2025-09-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_produit_303484_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_movemen_76afde_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_src_buc_308d2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_dst_buc_0b6c94_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_lot_cod_5106e2_idx',
        ),
    ]
