# Generated by Django 5.2.7 on 2025-12-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='stock_consumed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
