# Generated by Django 5.2.7 on 2026-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE_IN', 'Entrée achat'), ('CANCEL_PURCHASE', 'Annulation achat (sortie)'), ('ALLOCATE', 'Affectation réservé → bijouterie'), ('TRANSFER', 'Transfert entre bijouteries'), ('ADJUSTMENT', 'Ajustement manuel'), ('SALE_OUT', 'Sortie vente'), ('RETURN_IN', 'Retour client (entrée)'), ('CANCEL_SALE', 'Annulation vente'), ('VENDOR_ASSIGN', 'Affectation à un vendeur'), ('RECEIVE', 'Mise en rayon (rend vendable)')], max_length=32),
        ),
    ]
