# Generated by Django 5.2.7 on 2026-05-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_movement_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorymovement',
            name='uniq_sale_out_per_sale_line_source',
        ),
    ]
