# Generated by Django 5.2.5 on 2025-09-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='lot_code',
        ),
    ]
