# Generated by Django 5.2.5 on 2025-09-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventorymovement_lot_code'),
        ('purchase', '0004_achatproduitlot_alter_achat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.achatproduitlot'),
        ),
    ]
