# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='ouvrier',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvriers', to='store.bijouterie'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['active'], name='person_empl_active_9e4ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['nom', 'prenom'], name='person_empl_nom_c7722d_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrier',
            index=models.Index(fields=['active'], name='person_ouvr_active_8cbe9a_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrier',
            index=models.Index(fields=['type_ouvrier'], name='person_ouvr_type_ou_14d198_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrier',
            index=models.Index(fields=['nom', 'prenom'], name='person_ouvr_nom_c0fc82_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrier',
            index=models.Index(fields=['bijouterie', 'type_ouvrier'], name='person_ouvr_bijoute_dd4453_idx'),
        ),
    ]
