# Generated by Django 5.2.7 on 2026-05-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_initial'),
        ('store', '0003_alter_bijouterie_appliquer_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrier',
            name='adresse_atelier',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ouvrier',
            name='nom_atelier',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ouvrier',
            name='type_ouvrier',
            field=models.CharField(choices=[('interne', 'Interne à la bijouterie'), ('externe', 'Atelier externe')], db_index=True, default='interne', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ouvrier',
            index=models.Index(fields=['type_ouvrier'], name='person_ouvr_type_ou_14d198_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrier',
            index=models.Index(fields=['bijouterie', 'type_ouvrier'], name='person_ouvr_bijoute_dd4453_idx'),
        ),
    ]
