# Generated by Django 5.2.7 on 2026-05-05 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0002_initial'),
        ('sale', '0004_alter_client_options_client_address_client_cni_and_more'),
        ('store', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente paiement'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='paid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('mode_paiement', models.CharField(default='especes', max_length=30)),
                ('adresse_fournisseur', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='confirmed', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_matiere_premiere', to='store.bijouterie')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_matiere_premiere', to='purchase.fournisseur')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiereMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(choices=[('or', 'Or'), ('argent', 'Argent')], max_length=30)),
                ('poids', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('source', models.CharField(choices=[('rachat_client', 'Rachat client'), ('achat_fournisseur', 'Achat fournisseur'), ('rachat_client_cancel', 'Annulation rachat client'), ('achat_fournisseur_cancel', 'Annulation achat fournisseur'), ('remise_vente', 'Remise vente'), ('raffinage_out', 'Raffinage sortie'), ('raffinage_in', 'Raffinage entrée'), ('vente_poids', 'Vente par poids'), ('commande_client', 'Commande client'), ('vente_raffine', 'Vente raffinée')], default='rachat_client', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock_matiere_premiere.achatmatierepremiere')),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_matiere', to='store.bijouterie')),
                ('purete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_matiere', to='store.purete')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AchatMatierePremiereItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('matiere', models.CharField(choices=[('or', 'Or'), ('argent', 'Argent')], default='or', max_length=30)),
                ('poids', models.DecimalField(decimal_places=3, max_digits=14)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_matiere_premiere.achatmatierepremiere')),
                ('purete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.purete')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achat_matiere_item', to='stock_matiere_premiere.matierepremieremovement')),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiereStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(choices=[('or', 'Or'), ('argent', 'Argent')], default='or', max_length=30)),
                ('poids_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_matiere_premiere', to='store.bijouterie')),
                ('purete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_matiere_premiere', to='store.purete')),
            ],
            options={
                'ordering': ['bijouterie_id', 'matiere', 'purete_id'],
            },
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock_matiere_premiere.matierepremierestock'),
        ),
        migrations.CreateModel(
            name='RachatClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente paiement'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cni_client', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mode_paiement', models.CharField(default='especes', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adresse_client', models.CharField(max_length=255)),
                ('mention', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='confirmed', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bijouterie')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.client')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='rachat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock_matiere_premiere.rachatclient'),
        ),
        migrations.CreateModel(
            name='RachatClientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('matiere', models.CharField(default='or', max_length=50)),
                ('poids', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rachat_item', to='stock_matiere_premiere.matierepremieremovement')),
                ('purete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.purete')),
                ('rachat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_matiere_premiere.rachatclient')),
            ],
        ),
        migrations.CreateModel(
            name='Raffinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operation', models.CharField(max_length=50, unique=True)),
                ('matiere', models.CharField(choices=[('or', 'Or'), ('argent', 'Argent')], max_length=30)),
                ('poids_entree', models.DecimalField(decimal_places=3, max_digits=14)),
                ('poids_sortie', models.DecimalField(decimal_places=3, max_digits=14)),
                ('perte', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bijouterie')),
                ('purete_apres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='store.purete')),
                ('purete_avant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='store.purete')),
            ],
        ),
        migrations.CreateModel(
            name='StockRaffine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(choices=[('or', 'Or'), ('argent', 'Argent')], max_length=30)),
                ('poids_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bijouterie')),
                ('purete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.purete')),
            ],
        ),
        migrations.CreateModel(
            name='VenteMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vente', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source_stock', models.CharField(choices=[('avant_raffinage', 'Avant raffinage'), ('apres_raffinage', 'Après raffinage')], max_length=30)),
                ('matiere', models.CharField(choices=[('or', 'Or'), ('argent', 'Argent')], max_length=30)),
                ('poids', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('prix_gramme', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bijouterie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bijouterie')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sale.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_matiere_premiere', to=settings.AUTH_USER_MODEL)),
                ('purete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.purete')),
            ],
        ),
        migrations.AddConstraint(
            model_name='matierepremierestock',
            constraint=models.UniqueConstraint(fields=('bijouterie', 'matiere', 'purete'), name='uq_stock_matiere_unique'),
        ),
        migrations.AddConstraint(
            model_name='matierepremierestock',
            constraint=models.CheckConstraint(condition=models.Q(('poids_total__gte', 0)), name='ck_stock_matiere_positive'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['source'], name='stock_matie_source_d57267_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['bijouterie', 'matiere', 'purete'], name='stock_matie_bijoute_703a4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockraffine',
            constraint=models.UniqueConstraint(fields=('bijouterie', 'matiere', 'purete'), name='uq_stock_raffine_unique'),
        ),
    ]
