# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_matiere_premiere', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatmatierepremiere',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_matiere_premiere', to='store.bijouterie'),
        ),
    ]
