# Generated by Django 5.2.7 on 2026-05-31 15:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
        ('sale', '0009_rename_actif_modepaiement_active'),
        ('stock_matiere_premiere', '0002_achatmatierepremiere_uuid_rachatclient_uuid_and_more'),
        ('store', '0004_alter_produit_matiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achatmatierepremiere',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='achatmatierepremiereitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rachatclient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rachatclientitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='raffinage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockraffine',
            options={'ordering': ['bijouterie_id', 'matiere', 'purete_id']},
        ),
        migrations.AlterModelOptions(
            name='ventematierepremiere',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='raffinage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffinages_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raffinage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achatmatierepremiereitem',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=30),
        ),
        migrations.AlterField(
            model_name='achatmatierepremiereitem',
            name='poids',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='achatmatierepremiereitem',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_matiere_items', to='store.purete'),
        ),
        migrations.AlterField(
            model_name='matierepremieremovement',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], max_length=30),
        ),
        migrations.AlterField(
            model_name='matierepremierestock',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=30),
        ),
        migrations.AlterField(
            model_name='rachatclientitem',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=50),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffinages', to='store.bijouterie'),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=30),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='numero_operation',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='perte',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='poids_entree',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='poids_sortie',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='purete_apres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffinages_apres', to='store.purete'),
        ),
        migrations.AlterField(
            model_name='raffinage',
            name='purete_avant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffinages_avant', to='store.purete'),
        ),
        migrations.AlterField(
            model_name='stockraffine',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_raffines', to='store.bijouterie'),
        ),
        migrations.AlterField(
            model_name='stockraffine',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockraffine',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_raffines', to='store.purete'),
        ),
        migrations.AlterField(
            model_name='ventematierepremiere',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_matiere_premiere', to='store.bijouterie'),
        ),
        migrations.AlterField(
            model_name='ventematierepremiere',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes_matiere_premiere', to='sale.client'),
        ),
        migrations.AlterField(
            model_name='ventematierepremiere',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=30),
        ),
        migrations.AlterField(
            model_name='ventematierepremiere',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_matiere_premiere', to='store.purete'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiere',
            index=models.Index(fields=['payment_status'], name='stock_matie_payment_4fb570_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiere',
            index=models.Index(fields=['status'], name='stock_matie_status_951673_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiere',
            index=models.Index(fields=['created_at'], name='stock_matie_created_e86dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiereitem',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_54fd62_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiereitem',
            index=models.Index(fields=['purete'], name='stock_matie_purete__90cef4_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiereitem',
            index=models.Index(fields=['matiere', 'purete'], name='stock_matie_matiere_c0d663_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_bf9827_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['purete'], name='stock_matie_purete__8c0243_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['created_at'], name='stock_matie_created_8030d2_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremierestock',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_f21cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremierestock',
            index=models.Index(fields=['purete'], name='stock_matie_purete__37c7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremierestock',
            index=models.Index(fields=['updated_at'], name='stock_matie_updated_a812f8_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclient',
            index=models.Index(fields=['payment_status'], name='stock_matie_payment_2b36e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclient',
            index=models.Index(fields=['status'], name='stock_matie_status_88731e_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclient',
            index=models.Index(fields=['created_at'], name='stock_matie_created_c10483_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclientitem',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_5a4851_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclientitem',
            index=models.Index(fields=['purete'], name='stock_matie_purete__037d87_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_b75d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['created_at'], name='stock_matie_created_fedea1_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['bijouterie', 'matiere'], name='stock_matie_bijoute_411a26_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['purete_avant'], name='stock_matie_purete__ef3993_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['purete_apres'], name='stock_matie_purete__d26558_idx'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_e7f89e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['purete'], name='stock_matie_purete__02ed93_idx'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['updated_at'], name='stock_matie_updated_a88ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['bijouterie', 'matiere'], name='stock_matie_bijoute_93b2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['source_stock'], name='stock_matie_source__9c5c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_e5872c_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['purete'], name='stock_matie_purete__ac7908_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['created_at'], name='stock_matie_created_229ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['bijouterie', 'matiere'], name='stock_matie_bijoute_9ded21_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['bijouterie', 'created_at'], name='stock_matie_bijoute_e1b022_idx'),
        ),
        migrations.AddConstraint(
            model_name='raffinage',
            constraint=models.CheckConstraint(condition=models.Q(('perte__gte', 0)), name='ck_raffinage_perte_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockraffine',
            constraint=models.CheckConstraint(condition=models.Q(('poids_total__gte', 0)), name='ck_stock_raffine_positive'),
        ),
    ]
