# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0003_initial'),
        ('sale', '0003_initial'),
        ('stock_matiere_premiere', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achatmatierepremiere',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achatmatierepremiere',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_matiere_premiere', to='purchase.fournisseur'),
        ),
        migrations.AddField(
            model_name='achatmatierepremiere',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achatmatierepremiereitem',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_matiere_premiere.achatmatierepremiere'),
        ),
        migrations.AddField(
            model_name='achatmatierepremiereitem',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_matiere_items', to='store.purete'),
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock_matiere_premiere.achatmatierepremiere'),
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_matiere', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_matiere', to='store.purete'),
        ),
        migrations.AddField(
            model_name='achatmatierepremiereitem',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achat_matiere_item', to='stock_matiere_premiere.matierepremieremovement'),
        ),
        migrations.AddField(
            model_name='matierepremierestock',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_matiere_premiere', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='matierepremierestock',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_matiere_premiere', to='store.purete'),
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock_matiere_premiere.matierepremierestock'),
        ),
        migrations.AddField(
            model_name='rachatclient',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='rachatclient',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rachatclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.client'),
        ),
        migrations.AddField(
            model_name='rachatclient',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matierepremieremovement',
            name='rachat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock_matiere_premiere.rachatclient'),
        ),
        migrations.AddField(
            model_name='rachatclientitem',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rachat_item', to='stock_matiere_premiere.matierepremieremovement'),
        ),
        migrations.AddField(
            model_name='rachatclientitem',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.purete'),
        ),
        migrations.AddField(
            model_name='rachatclientitem',
            name='rachat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_matiere_premiere.rachatclient'),
        ),
        migrations.AddField(
            model_name='raffinage',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffinages', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='raffinage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffinages_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raffinage',
            name='purete_apres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffinages_apres', to='store.purete'),
        ),
        migrations.AddField(
            model_name='raffinage',
            name='purete_avant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffinages_avant', to='store.purete'),
        ),
        migrations.AddField(
            model_name='stockraffine',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_raffines', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='stockraffine',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_raffines', to='store.purete'),
        ),
        migrations.AddField(
            model_name='ventematierepremiere',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_matiere_premiere', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='ventematierepremiere',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes_matiere_premiere', to='sale.client'),
        ),
        migrations.AddField(
            model_name='ventematierepremiere',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_matiere_premiere', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventematierepremiere',
            name='purete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_matiere_premiere', to='store.purete'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiere',
            index=models.Index(fields=['payment_status'], name='stock_matie_payment_4fb570_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiere',
            index=models.Index(fields=['status'], name='stock_matie_status_951673_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiere',
            index=models.Index(fields=['created_at'], name='stock_matie_created_e86dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiereitem',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_54fd62_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiereitem',
            index=models.Index(fields=['purete'], name='stock_matie_purete__90cef4_idx'),
        ),
        migrations.AddIndex(
            model_name='achatmatierepremiereitem',
            index=models.Index(fields=['matiere', 'purete'], name='stock_matie_matiere_c0d663_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremierestock',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_f21cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremierestock',
            index=models.Index(fields=['purete'], name='stock_matie_purete__37c7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremierestock',
            index=models.Index(fields=['updated_at'], name='stock_matie_updated_a812f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='matierepremierestock',
            constraint=models.UniqueConstraint(fields=('bijouterie', 'matiere', 'purete'), name='uq_stock_matiere_unique'),
        ),
        migrations.AddConstraint(
            model_name='matierepremierestock',
            constraint=models.CheckConstraint(condition=models.Q(('poids_total__gte', 0)), name='ck_stock_matiere_positive'),
        ),
        migrations.AddIndex(
            model_name='rachatclient',
            index=models.Index(fields=['payment_status'], name='stock_matie_payment_2b36e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclient',
            index=models.Index(fields=['status'], name='stock_matie_status_88731e_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclient',
            index=models.Index(fields=['created_at'], name='stock_matie_created_c10483_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['source'], name='stock_matie_source_d57267_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_bf9827_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['purete'], name='stock_matie_purete__8c0243_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['created_at'], name='stock_matie_created_8030d2_idx'),
        ),
        migrations.AddIndex(
            model_name='matierepremieremovement',
            index=models.Index(fields=['bijouterie', 'matiere', 'purete'], name='stock_matie_bijoute_703a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclientitem',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_5a4851_idx'),
        ),
        migrations.AddIndex(
            model_name='rachatclientitem',
            index=models.Index(fields=['purete'], name='stock_matie_purete__037d87_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_b75d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['created_at'], name='stock_matie_created_fedea1_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['bijouterie', 'matiere'], name='stock_matie_bijoute_411a26_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['purete_avant'], name='stock_matie_purete__ef3993_idx'),
        ),
        migrations.AddIndex(
            model_name='raffinage',
            index=models.Index(fields=['purete_apres'], name='stock_matie_purete__d26558_idx'),
        ),
        migrations.AddConstraint(
            model_name='raffinage',
            constraint=models.CheckConstraint(condition=models.Q(('perte__gte', 0)), name='ck_raffinage_perte_positive'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_e7f89e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['purete'], name='stock_matie_purete__02ed93_idx'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['updated_at'], name='stock_matie_updated_a88ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockraffine',
            index=models.Index(fields=['bijouterie', 'matiere'], name='stock_matie_bijoute_93b2e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockraffine',
            constraint=models.UniqueConstraint(fields=('bijouterie', 'matiere', 'purete'), name='uq_stock_raffine_unique'),
        ),
        migrations.AddConstraint(
            model_name='stockraffine',
            constraint=models.CheckConstraint(condition=models.Q(('poids_total__gte', 0)), name='ck_stock_raffine_positive'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['source_stock'], name='stock_matie_source__9c5c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['matiere'], name='stock_matie_matiere_e5872c_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['purete'], name='stock_matie_purete__ac7908_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['created_at'], name='stock_matie_created_229ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['bijouterie', 'matiere'], name='stock_matie_bijoute_9ded21_idx'),
        ),
        migrations.AddIndex(
            model_name='ventematierepremiere',
            index=models.Index(fields=['bijouterie', 'created_at'], name='stock_matie_bijoute_e1b022_idx'),
        ),
    ]
