# Generated by Django 5.2.7 on 2026-01-05 06:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=32)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé')], default='non_paye', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('type_facture', models.CharField(choices=[('proforma', 'Proforma'), ('facture', 'facture'), ('acompte', 'Facture d’acompte'), ('finale', 'Facture finale')], default='proforma', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Factures',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile')], default='cash', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vente', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_vente_grammes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sous_total_prix_vente_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Remise (montant FCFA)', max_digits=12, null=True)),
                ('autres', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Autres montants (emballage, etc.)', max_digits=12)),
            ],
        ),
    ]
