# Generated by Django 5.1.3 on 2024-12-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Payé', 'Payé')], default='En attente', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Factures',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_facture', to='sale.facture')),
            ],
            options={
                'verbose_name_plural': 'Paiements',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='sale.client')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_vente', to='sale.vente'),
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_vente_grammes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sous_total_prix_vent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('tax_inclue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venteProduit_produit', to='store.produit')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='sale.vente')),
            ],
        ),
    ]
