# Generated by Django 5.2.7 on 2026-08-06 21:20

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('numero_facture', models.CharField(editable=False, max_length=32)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('appliquer_tva', models.BooleanField(default=False)),
                ('taux_tva', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Partiellement payé'), ('paye', 'Payé')], default='non_paye', max_length=20)),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('type_facture', models.CharField(choices=[('proforma', 'Proforma'), ('facture', 'Facture'), ('acompte', 'Facture d’acompte'), ('finale', 'Facture finale')], default='proforma', max_length=20)),
                ('integrity_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='factures/qr/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('stock_consumed', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('est_mode_depot', models.BooleanField(default=False)),
                ('necessite_reference', models.BooleanField(default=False)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='PaiementLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Référence transaction Wave / OM / banque / TPE', max_length=255, null=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='Référence retournée par Stripe, PayDunya, CinetPay, banque ou TPE', max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, help_text='Lien de paiement en ligne si applicable', null=True)),
                ('payment_token', models.CharField(blank=True, help_text='Token de paiement externe', max_length=255, null=True)),
                ('callback_received', models.BooleanField(default=False, help_text='Indique si le callback/confirmation_paiement du fournisseur a été reçu')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('source_vente', models.CharField(choices=[('magasin', 'Magasin'), ('ecommerce', 'E-commerce'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook')], db_index=True, default='magasin', max_length=20)),
                ('numero_vente', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_vente_grammes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True)),
                ('autres', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True)),
                ('cni', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numéro CNI')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['telephone'], name='sale_client_telepho_cfa69a_idx'), models.Index(fields=['cni'], name='sale_client_cni_841354_idx')],
            },
        ),
    ]
