# Generated by Django 5.2.7 on 2026-04-22 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('sale', '0001_initial'),
        ('staff', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commande_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='order.commandeclient'),
        ),
        migrations.AddField(
            model_name='invoicecounter',
            name='bijouterie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_counters', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='staff.cashier'),
        ),
    ]
