# Generated by Django 4.2 on 2025-05-16 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venteproduits_vendor', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='autres',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional info', max_digits=5),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount', max_digits=5, null=True),
        ),
    ]
