# Generated by Django 5.2.5 on 2025-09-14 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0002_initial'),
        ('store', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_validation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='sale.facture'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='sale.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_vente', to='sale.vente'),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venteProduit_produit', to='store.produit'),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venteproduits_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='sale.vente'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='sale_paieme_date_pa_8072d6_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['created_by'], name='sale_paieme_created_a735a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['cashier'], name='sale_paieme_cashier_ef7074_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture', 'date_paiement'], name='sale_paieme_facture_8deb4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(
                check=models.Q(montant_paye__gt=0),
                name='paiement_montant_gt_0',
            ),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['created_at'], name='sale_vente_created_aadd28_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['numero_vente'], name='sale_vente_numero__6c187d_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero_facture'], name='sale_factur_numero__5be43f_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_creation'], name='sale_factur_date_cr_39a5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['status'], name='sale_factur_status_2cb412_idx'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(
                check=models.Q(montant_total__gte=0),
                name='facture_montant_total_gte_0',
            ),
        ),
    ]
