# Generated by Django 4.2 on 2025-07-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_commandeproduitclient_options_and_more'),
        ('sale', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='commande_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_en_ventes', to='order.commandeclient'),
        ),
    ]
