# Generated by Django 4.2 on 2025-05-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_vente_created_by_venteproduit_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='numero_vente',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
