# Generated by Django 5.2.7 on 2026-04-22 23:22

import django.db.models.deletion
import sale.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte_depot', '0002_initial'),
        ('sale', '0002_initial'),
        ('store', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_validation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='sale.facture'),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='compte_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_paiement', to='compte_depot.comptedepot'),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='mode_paiement',
            field=models.ForeignKey(default=sale.models.get_default_mode_paiement, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_paiement', to='sale.modepaiement'),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sale.paiement'),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='transaction_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_paiement', to='compte_depot.comptedepottransaction'),
        ),
        migrations.AddField(
            model_name='vente',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='store.bijouterie'),
        ),
        migrations.AddField(
            model_name='vente',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='sale.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_livrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_vente', to='sale.vente'),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.produit'),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vente_produits', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sale.vente'),
        ),
        migrations.AddIndex(
            model_name='invoicecounter',
            index=models.Index(fields=['bijouterie', 'day'], name='sale_invoic_bijoute_7661c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicecounter',
            constraint=models.UniqueConstraint(fields=('bijouterie', 'day'), name='uniq_invoice_counter_per_shop_day'),
        ),
        migrations.AddIndex(
            model_name='paiementligne',
            index=models.Index(fields=['paiement'], name='sale_paieme_paiemen_3e2bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementligne',
            index=models.Index(fields=['mode_paiement'], name='sale_paieme_mode_pa_c60733_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiementligne',
            constraint=models.CheckConstraint(condition=models.Q(('montant_paye__gt', 0)), name='paiement_ligne_montant_paye_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='paiementligne',
            constraint=models.UniqueConstraint(fields=('paiement', 'mode_paiement'), name='uniq_mode_par_paiement'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['created_at'], name='sale_vente_created_aadd28_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['numero_vente'], name='sale_vente_numero__6c187d_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['vendor', 'created_at'], name='sale_vente_vendor__553c58_idx'),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gte', 0)), name='vente_montant_total_gte_0'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero_facture'], name='sale_factur_numero__5be43f_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_creation'], name='sale_factur_date_cr_39a5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['status'], name='sale_factur_status_2cb412_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['type_facture'], name='sale_factur_type_fa_e49010_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['bijouterie', 'date_creation'], name='sale_factur_bijoute_33f431_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['commande_client'], name='sale_factur_command_3bb3f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('montant_ht__gte', 0)), name='facture_montant_ht_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0)), name='facture_taux_tva_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__lte', 100)), name='facture_taux_tva_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('montant_tva__gte', 0)), name='facture_montant_tva_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gte', 0)), name='facture_montant_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.UniqueConstraint(fields=('bijouterie', 'numero_facture'), name='uniq_invoice_per_shop'),
        ),
        migrations.AddIndex(
            model_name='venteproduit',
            index=models.Index(fields=['vente'], name='sale_ventep_vente_i_f3f863_idx'),
        ),
        migrations.AddIndex(
            model_name='venteproduit',
            index=models.Index(fields=['vendor'], name='sale_ventep_vendor__e5473f_idx'),
        ),
        migrations.AddIndex(
            model_name='venteproduit',
            index=models.Index(fields=['produit'], name='sale_ventep_produit_8579eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='venteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gte', 1)), name='ck_venteproduit_qty_gte_1'),
        ),
    ]
