# Generated by Django 4.2 on 2025-06-13 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('sale', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='commande_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commend_en_ventes', to='order.commandeclient'),
        ),
    ]
