# Generated by Django 5.2.7 on 2026-05-05 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='client',
            name='cni',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Numéro CNI'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['telephone'], name='sale_client_telepho_cfa69a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['cni'], name='sale_client_cni_841354_idx'),
        ),
    ]
