# Generated by Django 5.2.7 on 2025-12-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='store.bijouterie'),
        ),
    ]
