# Generated by Django 4.2 on 2025-08-30 09:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('sale', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='vendor.cashier'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé')], default='non_paye', max_length=20),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero_facture'], name='sale_factur_numero__5be43f_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_creation'], name='sale_factur_date_cr_39a5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['status'], name='sale_factur_status_2cb412_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='sale_paieme_date_pa_8072d6_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['created_by'], name='sale_paieme_created_a735a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['cashier'], name='sale_paieme_cashier_ef7074_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture', 'date_paiement'], name='sale_paieme_facture_8deb4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(check=models.Q(('montant_total__gte', 0)), name='facture_montant_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(check=models.Q(('montant_paye__gt', 0)), name='paiement_montant_gt_0'),
        ),
    ]
