# Generated by Django 5.2.7 on 2026-08-20 23:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='frais_transaction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
