# Generated by Django 4.2 on 2025-07-23 10:26

from django.db import migrations, models
# Generated by Django 4.2 on 2025-07-20 22:06

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_vente_commande_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='commande_source',
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('vente_directe', 'Vente directe'), ('acompte', 'Facture d’acompte'), ('finale', 'Facture finale')], default='vente_directe', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('non_payé', 'Non Payé'), ('payé', 'Non Payé')], default='non_payé', max_length=20),
        ),
    ]
