# Generated by Django 4.2 on 2025-05-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_vente_numero_vente_alter_facture_montant_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='numero_vente',
        ),
    ]
