# Generated by Django 5.2.7 on 2025-12-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_vente_bijouterie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='delivery_status',
        ),
    ]
