# Generated by Django 4.2 on 2025-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_remove_vente_numero_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='numero_vente',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
