# Generated by Django 4.2 on 2025-08-31 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_paiement_cashier_alter_facture_montant_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venteproduit',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Discount (montant)', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['created_at'], name='sale_vente_created_aadd28_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['numero_vente'], name='sale_vente_numero__6c187d_idx'),
        ),
        migrations.AddIndex(
            model_name='venteproduit',
            index=models.Index(fields=['vente'], name='sale_ventep_vente_i_f3f863_idx'),
        ),
        migrations.AddIndex(
            model_name='venteproduit',
            index=models.Index(fields=['vendor'], name='sale_ventep_vendor__e5473f_idx'),
        ),
        migrations.AddConstraint(
            model_name='venteproduit',
            constraint=models.CheckConstraint(check=models.Q(('quantite__gte', 1)), name='vente_produit_quantite_gte_1'),
        ),
    ]
