# Generated by Django 5.2.7 on 2026-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_client_options_client_address_client_cni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
