# Generated by Django 4.2 on 2025-08-31 17:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_venteproduit_options_alter_venteproduit_remise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteproduit',
            name='autres',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional info (montant)', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='venteproduit',
            index=models.Index(fields=['produit'], name='sale_ventep_produit_8579eb_idx'),
        ),
    ]
