# Generated by Django 4.2 on 2025-05-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_vente_numero_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='numero_vente',
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
