# Generated by Django 5.2.7 on 2026-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='appliquer_tva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiementligne',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence transaction Wave / OM / banque', max_length=255, null=True),
        ),
    ]
