# Generated by Django 5.2.7 on 2026-08-27 01:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
        ('sale', '0005_client_user_alter_vente_vendor'),
        ('store', '0004_produit_pourcentage_occasion'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facture',
            name='facture_taux_tva_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='facture',
            name='facture_taux_tva_lte_100',
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='pourcentage_occasion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__isnull', True), ('taux_tva__lte', 100), _connector='OR'), name='facture_taux_tva_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='venteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('prix_vente_grammes__gte', 0)), name='ck_venteproduit_prix_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='venteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('montant_ht__gte', 0)), name='ck_venteproduit_montant_ht_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='venteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gte', 0)), name='ck_venteproduit_montant_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='venteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('pourcentage_occasion__gte', 0)), name='ck_venteproduit_occasion_gte_0'),
        ),
    ]
