# Generated by Django 5.2.7 on 2026-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_facture_appliquer_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
