# Generated by Django 4.2 on 2025-05-22 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_remove_vente_numero_vente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venteproduit',
            old_name='tax_inclue',
            new_name='prix_ttc',
        ),
        migrations.AddField(
            model_name='vente',
            name='numero_vente',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='vente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='sale.vente'),
            preserve_default=False,
        ),
    ]
