# Generated by Django 4.2 on 2025-09-01 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_venteproduit_autres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venteproduit',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='venteproduit',
            name='vente_produit_quantite_gte_1',
        ),
        migrations.RemoveIndex(
            model_name='venteproduit',
            name='sale_ventep_vente_i_f3f863_idx',
        ),
        migrations.RemoveIndex(
            model_name='venteproduit',
            name='sale_ventep_vendor__e5473f_idx',
        ),
        migrations.RemoveIndex(
            model_name='venteproduit',
            name='sale_ventep_produit_8579eb_idx',
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='autres',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Autres montants (emballage, etc.)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Remise (montant FCFA)', max_digits=12, null=True),
        ),
    ]
