# Generated by Django 5.2.7 on 2026-05-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
        ('sale', '0007_alter_facture_montant_tva_alter_facture_taux_tva'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facture',
            name='facture_taux_tva_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='facture',
            name='facture_montant_tva_gte_0',
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__isnull', True), ('taux_tva__gte', 0), _connector='OR'), name='facture_taux_tva_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('montant_tva__isnull', True), ('montant_tva__gte', 0), _connector='OR'), name='facture_montant_tva_gte_0'),
        ),
    ]
