# Generated by Django 4.2 on 2025-05-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_rename_tax_inclue_venteproduit_prix_ttc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venteproduit',
            old_name='sous_total_prix_vent',
            new_name='sous_total_prix_vente_ht',
        ),
    ]
