# Generated by Django 4.2 on 2025-05-28 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0008_rename_sous_total_prix_vent_venteproduit_sous_total_prix_vente_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_validation', to=settings.AUTH_USER_MODEL),
        ),
    ]
