# Generated by Django 5.2.7 on 2026-05-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_remove_facture_facture_taux_tva_gte_0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modepaiement',
            old_name='actif',
            new_name='active',
        ),
    ]
