# Generated by Django 5.2.7 on 2026-06-06 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_rename_actif_modepaiement_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='callback_received',
            field=models.BooleanField(default=False, help_text='Indique si le callback/webhook du fournisseur a été reçu'),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Lien de paiement en ligne si applicable', null=True),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='payment_token',
            field=models.CharField(blank=True, help_text='Token de paiement externe', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiementligne',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Référence retournée par Stripe, PayDunya, CinetPay, banque ou TPE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='source_vente',
            field=models.CharField(choices=[('magasin', 'Magasin'), ('ecommerce', 'E-commerce'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook')], db_index=True, default='magasin', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paiementligne',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence transaction Wave / OM / banque / TPE', max_length=255, null=True),
        ),
    ]
