# Generated by Django 5.2.7 on 2026-08-06 21:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDepot',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.client')),
                ('photo', models.ImageField(blank=True, default='client/default.jpg', null=True, upload_to='client/')),
            ],
            options={
                'verbose_name': 'Client (compte dépôt)',
                'verbose_name_plural': 'Clients (compte dépôt)',
            },
            bases=('sale.client',),
        ),
        migrations.CreateModel(
            name='CompteDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(db_index=True, max_length=30, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompteDepotTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('TERMINE', 'Terminé'), ('ECHOUE', 'Échoué'), ('ATTENTE', 'En attente')], default='TERMINE', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('solde_avant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Transaction compte dépôt',
                'verbose_name_plural': 'Transactions compte dépôt',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
