# Generated by Django 5.2.5 on 2025-10-14 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte_depot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comptedepot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='compte_depot.comptedepot'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comptedepot',
            index=models.Index(fields=['client'], name='compte_depo_client__9a5f46_idx'),
        ),
        migrations.AddIndex(
            model_name='comptedepot',
            index=models.Index(fields=['date_creation'], name='compte_depo_date_cr_24bceb_idx'),
        ),
        migrations.AddConstraint(
            model_name='comptedepot',
            constraint=models.CheckConstraint(condition=models.Q(('solde__gte', 0)), name='ck_compte_depot_solde_gte_0'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['compte', 'date_transaction'], name='compte_depo_compte__669e44_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['statut'], name='compte_depo_statut_332349_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type_transaction'], name='compte_depo_type_tr_12d9d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='ck_transaction_montant_gt_0'),
        ),
    ]
