# Generated by Django 5.2.7 on 2026-04-22 23:22

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte_depot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comptedepot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comptedepottransaction',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='compte_depot.comptedepot'),
        ),
        migrations.AddField(
            model_name='comptedepottransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comptedepot',
            index=models.Index(fields=['client'], name='compte_depo_client__9a5f46_idx'),
        ),
        migrations.AddIndex(
            model_name='comptedepot',
            index=models.Index(fields=['date_creation'], name='compte_depo_date_cr_24bceb_idx'),
        ),
        migrations.AddConstraint(
            model_name='comptedepot',
            constraint=models.CheckConstraint(condition=models.Q(('solde__gte', 0)), name='ck_compte_depot_solde_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='comptedepottransaction',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='ck_compte_depot_tx_montant_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='comptedepottransaction',
            constraint=models.CheckConstraint(condition=models.Q(('solde_avant__gte', 0)), name='ck_compte_depot_tx_solde_avant_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='comptedepottransaction',
            constraint=models.CheckConstraint(condition=models.Q(('solde_apres__gte', 0)), name='ck_compte_depot_tx_solde_apres_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='comptedepottransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_transaction', 'DEPOT'), ('solde_apres', django.db.models.expressions.CombinedExpression(models.F('solde_avant'), '+', models.F('montant')))), models.Q(('type_transaction', 'RETRAIT'), ('solde_apres', django.db.models.expressions.CombinedExpression(models.F('solde_avant'), '-', models.F('montant')))), _connector='OR'), name='ck_compte_depot_tx_coherence_solde'),
        ),
    ]
