# Generated by Django 5.1.3 on 2025-06-20 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte_depot', '0002_initial'),
        ('sale', '0003_vente_commande_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDepot',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.client')),
                ('CNI', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, default='client.jpg', null=True, upload_to='client/')),
            ],
            bases=('sale.client',),
        ),
        migrations.RemoveField(
            model_name='comptebancaire',
            name='client',
        ),
        migrations.RemoveField(
            model_name='comptebancaire',
            name='created_by',
        ),
        migrations.CreateModel(
            name='CompteDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=30, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_depot', to='compte_depot.clientdepot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='compte_depot.comptedepot'),
        ),
        migrations.DeleteModel(
            name='ClientBanque',
        ),
        migrations.DeleteModel(
            name='CompteBancaire',
        ),
    ]
