# Generated by Django 5.2.7 on 2026-05-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte_depot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdepot',
            name='address',
        ),
    ]
