# Generated by Django 5.2.7 on 2026-08-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte_depot', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptedepot',
            name='updated_at',
        ),
    ]
