# Generated by Django 5.2.7 on 2026-05-05 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte_depot', '0003_remove_clientdepot_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptedepot',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comptedepot',
            name='compte_depo_date_cr_24bceb_idx',
        ),
        migrations.RenameField(
            model_name='comptedepot',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='comptedepot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='comptedepot',
            index=models.Index(fields=['created_at'], name='compte_depo_created_04b957_idx'),
        ),
    ]
