# Generated by Django 5.2.7 on 2026-05-24 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte_depot', '0004_alter_comptedepot_options_and_more'),
        ('store', '0003_alter_bijouterie_appliquer_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdepot',
            name='bijouterie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_depot', to='store.bijouterie'),
        ),
    ]
