# Generated by Django 5.2.7 on 2026-07-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte_depot', '0005_clientdepot_bijouterie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdepot',
            name='CNI',
        ),
    ]
