# Generated by Django 4.2 on 2025-06-13 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('sale', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='order-client.jpg', null=True, upload_to='orders/client')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_client', to='sale.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduitClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_libre', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_prevue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('commande_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='order.commandeclient')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.produit')),
            ],
            options={
                'verbose_name': 'Produit commandé',
                'verbose_name_plural': 'Produits commandés',
                'ordering': ['-id'],
            },
        ),
    ]
