# Generated by Django 4.2 on 2025-08-05 22:34

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=100, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_acompte', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'acompte")),
                ('modification_date_acompte', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('en_attente_acompte', "En attente d'acompte"), ('en_attente', 'En attente'), ('payee', 'Payée')], default='en_attente_acompte', max_length=30)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='order-client.jpg', null=True, upload_to='orders/client')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduitClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant')], default='F', max_length=2, null=True)),
                ('taille', models.CharField(blank=True, max_length=7, null=True)),
                ('matiere', models.CharField(blank=True, choices=[('or', 'Or'), ('argent', 'Argent'), ('mixte', 'Mixte')], default='or', max_length=50, null=True)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_gramme', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('personnalise', models.BooleanField(default=False, help_text='Cochez si ce produit est personnalisé (et non un produit officiel)')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_prevue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorie')),
                ('commande_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_produits_client', to='order.commandeclient')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marque')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.modele')),
                ('purete', models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_produits_purete', to='store.purete')),
            ],
        ),
    ]
