# Generated by Django 4.2 on 2025-08-17 19:15

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('store', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduitclient',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorie'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='commande_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_produits_client', to='order.commandeclient'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marque'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.modele'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='purete',
            field=models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_produits_purete', to='store.purete'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_client', to='sale.client'),
        ),
    ]
