<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-03 09:47
=======
# Generated by Django 4.2 on 2025-08-25 09:14
>>>>>>> 949a9334 (en cours avant merge)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('store', '0001_initial'),
>>>>>>> 949a9334 (en cours avant merge)
        ('order', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_client', to='sale.client'),
        ),
    ]
