# Generated by Django 5.1.3 on 2025-06-20 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('sale', '0003_vente_commande_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_commandes', to='sale.client'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['date_commande'], name='order_comma_date_co_ed86eb_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['statut'], name='order_comma_statut_800ecb_idx'),
        ),
    ]
