<<<<<<< HEAD
# Generated by Django 4.2 on 2025-07-03 08:26
=======
# Generated by Django 4.2 on 2025-06-28 01:44
>>>>>>> d77abd2 (sauvegard les changement au niveau du order)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('order', '0002_initial'),
=======
>>>>>>> d77abd2 (sauvegard les changement au niveau du order)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['date_commande'], name='order_comma_date_co_ed86eb_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['statut'], name='order_comma_statut_800ecb_idx'),
        ),
    ]
