# Generated by Django 5.2.5 on 2025-10-14 00:33

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_commande', to='order.commandeclient'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorie'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='commande_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_produits_client', to='order.commandeclient'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marque'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.modele'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='purete',
            field=models.ForeignKey(blank=True, default=store.models.get_default_purete, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_produits_purete', to='store.purete'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['date_commande'], name='order_comma_date_co_ed86eb_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['statut'], name='order_comma_statut_800ecb_idx'),
        ),
    ]
