# Generated by Django 5.2.7 on 2026-05-24 23:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
        ('person', '0002_initial'),
        ('sale', '0009_rename_actif_modepaiement_active'),
        ('store', '0003_alter_bijouterie_appliquer_tva_and_more'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='ouvrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_clients', to='person.ouvrier'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='description_commande',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='matiere',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent')], default='or', max_length=20),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='poids_envoye_ouvrier',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='poids_perte',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='poids_retour_ouvrier',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='purete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.purete'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['ouvrier'], name='order_comma_ouvrier_bb3e33_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['statut', 'ouvrier'], name='order_comma_statut_77ac4a_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclienthistorique',
            index=models.Index(fields=['commande'], name='order_comma_command_686cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclienthistorique',
            index=models.Index(fields=['nouveau_statut'], name='order_comma_nouveau_11198b_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclienthistorique',
            index=models.Index(fields=['changed_at'], name='order_comma_changed_9120ba_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeproduitclient',
            index=models.Index(fields=['commande'], name='order_comma_command_c08255_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeproduitclient',
            index=models.Index(fields=['produit'], name='order_comma_produit_560be3_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeproduitclient',
            index=models.Index(fields=['purete'], name='order_comma_purete__d6e632_idx'),
        ),
        migrations.DeleteModel(
            name='Ouvrier',
        ),
    ]
