# Generated by Django 4.2 on 2025-07-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeproduitclient',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='commandeproduitclient',
            name='poids',
        ),
    ]
