# Generated by Django 4.2 on 2025-07-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_commandeproduitclient_marque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_fabrication', 'En fabrication'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=100, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_commande', to='order.commandeclient')),
            ],
        ),
    ]
