# Generated by Django 4.2 on 2025-07-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('order', '0005_alter_commandeclient_statut_boncommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduitclient',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marque'),
        ),
        migrations.AddField(
            model_name='commandeproduitclient',
            name='poids',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
            preserve_default=False,
        ),
    ]
