# Generated by Django 4.2 on 2025-07-07 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_commandeproduitclient_marque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_acompte',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date de l'acompte"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boncommande',
            name='modification_date_acompte',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='statut',
            field=models.CharField(choices=[('en_attente_acompte', "En attente d'acompte"), ('en_attente', 'En attente'), ('payee', 'Payée')], default='en_attente_acompte', max_length=30),
        ),
    ]
