# Generated by Django 4.2 on 2025-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_boncommande_date_acompte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduitclient',
            name='genre',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('E', 'Enfant')], default='F', max_length=2, null=True),
        ),
    ]
