# Generated by Django 4.2 on 2025-07-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_commandeproduitclient_options_and_more'),
        ('order', '0008_alter_commandeproduitclient_genre'),
    ]

    operations = [
    ]
