# Generated by Django 4.2 on 2025-07-23 10:26
# Generated by Django 4.2 on 2025-07-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_merge_20250723_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeproduitclient',
            name='categorie_personnalisee',
        ),
        migrations.RemoveField(
            model_name='commandeproduitclient',
            name='marque_personnalisee',
        ),
        migrations.RemoveField(
            model_name='commandeproduitclient',
            name='poids_prevu',
        ),
        migrations.RemoveField(
            model_name='commandeproduitclient',
            name='type_personnalise',
        ),
    ]
