# Generated by Django 4.2 on 2025-07-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_merge_20250720_2203'),
        ('order', '0010_remove_commandeproduitclient_categorie_personnalisee_and_more'),
    ]

    operations = [
    ]
